name: yum_quick
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.3
  google_nav_bar: ^5.0.7
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_database: ^11.2.0
  firebase_core: ^3.8.1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/LeagueSpartan-Light.ttf
          weight: 300
    - family: Inter
      fonts:
          - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
            weight: 900

